/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Controlador;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class MejoresPuntuaciones extends javax.swing.JPanel {

    /**
     * Creates new form MejoresPuntuaciones
     */
    
    Controlador controlador;
    public MejoresPuntuaciones() {
        initComponents();
    }

    public void mejoresPuntuaciones(String[] informacion)
     {
       jl_PrimerLugar.setText(informacion[0]);
       jl_Puntuacion1.setText(informacion[1]);
    
     }
    
    public void agregarEventos(Controlador controlador)
    {
        this.controlador=controlador;
        this.btn_ok.addActionListener(controlador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        jl_PrimerLugar = new javax.swing.JLabel();
        jl_Puntuacion1 = new javax.swing.JLabel();
        jl_Trofeos = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setOpaque(false);
        setLayout(null);

        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok.png"))); // NOI18N
        btn_ok.setActionCommand("ok");
        btn_ok.setContentAreaFilled(false);
        btn_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btn_ok);
        btn_ok.setBounds(390, 260, 140, 60);

        jl_PrimerLugar.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 60)); // NOI18N
        jl_PrimerLugar.setForeground(new java.awt.Color(255, 199, 50));
        jl_PrimerLugar.setText("----");
        add(jl_PrimerLugar);
        jl_PrimerLugar.setBounds(300, 70, 240, 140);

        jl_Puntuacion1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 70)); // NOI18N
        jl_Puntuacion1.setForeground(new java.awt.Color(255, 255, 255));
        jl_Puntuacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Puntuacion1.setText("---");
        add(jl_Puntuacion1);
        jl_Puntuacion1.setBounds(230, 190, 180, 80);

        jl_Trofeos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salonDeLaFama.png"))); // NOI18N
        add(jl_Trofeos);
        jl_Trofeos.setBounds(0, 0, 536, 376);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jl_PrimerLugar;
    private javax.swing.JLabel jl_Puntuacion1;
    private javax.swing.JLabel jl_Trofeos;
    // End of variables declaration//GEN-END:variables
}
