/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Controlador;
import java.applet.AudioClip;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class MenuInicio extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    AudioClip sonidoIni;
    
    Controlador controlador;
    public MenuInicio() {
        this.setLocation(550, 100);
        initComponents();
        musicaInicio();
        controlador= new Controlador(this);
        ventanaInicio2.agregarEventos(controlador);
        instrucciones1.agregarEventos(controlador);
        instrucciones1.setVisible(false);
        
    }
    
    
    public void setVisibleFalse()
    {
        instrucciones1.setVisible(false);
    }
    public void setVisibleTrue()
    {
        instrucciones1.setVisible(true);
    }
    
    
    public void musicaInicio()
    {
     
        sonidoIni=java.applet.Applet.newAudioClip(getClass().getResource("/audios/LightCaves.wav"));
        sonidoIni.play();
        
    }
            
    public void detenerMusica()
    {
        sonidoIni.stop();
    }

 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicio().setVisible(true);
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrucciones1 = new vista.Instrucciones();
        jl_GloboAmarillo = new javax.swing.JLabel();
        ventanaInicio2 = new vista.ventanaInicio();
        jl_GloboMorado = new javax.swing.JLabel();
        jl_Globo = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(571, 768));
        setPreferredSize(new java.awt.Dimension(571, 768));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout instrucciones1Layout = new javax.swing.GroupLayout(instrucciones1);
        instrucciones1.setLayout(instrucciones1Layout);
        instrucciones1Layout.setHorizontalGroup(
            instrucciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        instrucciones1Layout.setVerticalGroup(
            instrucciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(instrucciones1);
        instrucciones1.setBounds(60, 70, 470, 620);

        jl_GloboAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/globoAmarillo.png"))); // NOI18N
        getContentPane().add(jl_GloboAmarillo);
        jl_GloboAmarillo.setBounds(70, 340, 80, 110);
        getContentPane().add(ventanaInicio2);
        ventanaInicio2.setBounds(100, 160, 570, 803);

        jl_GloboMorado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/globoMorado.png"))); // NOI18N
        getContentPane().add(jl_GloboMorado);
        jl_GloboMorado.setBounds(450, 70, 70, 100);

        jl_Globo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gifglobo.gif"))); // NOI18N
        getContentPane().add(jl_Globo);
        jl_Globo.setBounds(220, 430, 160, 270);

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jl_Fondo);
        jl_Fondo.setBounds(0, -2360, 570, 3088);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.Instrucciones instrucciones1;
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Globo;
    private javax.swing.JLabel jl_GloboAmarillo;
    private javax.swing.JLabel jl_GloboMorado;
    private vista.ventanaInicio ventanaInicio2;
    // End of variables declaration//GEN-END:variables
}
