/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Controlador;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class NuevoRecord extends javax.swing.JPanel {

    /**
     * Creates new form NuevoRecord
     */
    
    Controlador controlador;
    public NuevoRecord() {
        initComponents();
    }

    
    public void cambiarNombre(String puntuacion)
     {
      
             jl_Puntuacion.setText(""+puntuacion);
         
         
     }
    
    public String[] enviarInformacion()
    {
        String informacion[]=new String[3];
        informacion[0]=this.jt_Nombre.getText();
        informacion[1]=this.jl_Puntuacion.getText();
        
        
        return informacion;
    }
    
    public void resetearPanel()
    {
        jt_Nombre.setText("");
        btn_Aceptar.setEnabled(false);
    }
    
    
    public void agregarEventos(Controlador controlador)
    {
        this.controlador=controlador;
        panelBotones1.agregarEventos(controlador);
        btn_Aceptar.addActionListener(controlador);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Puntuacion = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        btn_Aceptar = new javax.swing.JButton();
        panelBotones1 = new vista.PanelBotones();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jl_Puntuacion.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 100)); // NOI18N
        jl_Puntuacion.setForeground(new java.awt.Color(255, 199, 50));
        jl_Puntuacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Puntuacion.setText("Punt");
        add(jl_Puntuacion);
        jl_Puntuacion.setBounds(120, 160, 280, 120);

        jt_Nombre.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 11)); // NOI18N
        jt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NombreActionPerformed(evt);
            }
        });
        add(jt_Nombre);
        jt_Nombre.setBounds(220, 270, 100, 30);

        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Chec.png"))); // NOI18N
        btn_Aceptar.setActionCommand("Aceptar");
        btn_Aceptar.setContentAreaFilled(false);
        add(btn_Aceptar);
        btn_Aceptar.setBounds(310, 250, 73, 60);
        add(panelBotones1);
        panelBotones1.setBounds(80, 240, 460, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NuevoRecord.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 903);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jl_Puntuacion;
    private javax.swing.JTextField jt_Nombre;
    private vista.PanelBotones panelBotones1;
    // End of variables declaration//GEN-END:variables
}
