/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Controlador;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class PanelBotones extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotones
     */
    Controlador controlador;
    public PanelBotones() {
        initComponents();
    }

    
    public void agregarEventos(Controlador controlador)
    {
        this.controlador=controlador;
        this.btn_Home.addActionListener(controlador);
        this.btn_Record.addActionListener(controlador);
        this.btn_VolverJugar.addActionListener(controlador);
        this.btn_Salir.addActionListener(controlador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Record = new javax.swing.JButton();
        btn_Home = new javax.swing.JButton();
        btn_VolverJugar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setOpaque(false);
        setLayout(null);

        btn_Record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoRecords.png"))); // NOI18N
        btn_Record.setActionCommand("Record");
        btn_Record.setContentAreaFilled(false);
        add(btn_Record);
        btn_Record.setBounds(0, 60, 127, 103);

        btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoHome.png"))); // NOI18N
        btn_Home.setActionCommand("Home");
        btn_Home.setBorderPainted(false);
        btn_Home.setContentAreaFilled(false);
        add(btn_Home);
        btn_Home.setBounds(240, 60, 127, 103);

        btn_VolverJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoVolver.png"))); // NOI18N
        btn_VolverJugar.setActionCommand("VolverJugar");
        btn_VolverJugar.setContentAreaFilled(false);
        add(btn_VolverJugar);
        btn_VolverJugar.setBounds(110, 90, 145, 119);

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoSalir.png"))); // NOI18N
        btn_Salir.setActionCommand("Salir");
        btn_Salir.setContentAreaFilled(false);
        add(btn_Salir);
        btn_Salir.setBounds(350, 40, 87, 63);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Home;
    private javax.swing.JButton btn_Record;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_VolverJugar;
    // End of variables declaration//GEN-END:variables
}
