/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.Controlador;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class ventanaInicio extends javax.swing.JPanel {

    /**
     * Creates new form ventanaInicio
     */
    
    Controlador controlador;
    public ventanaInicio() {
        initComponents();
    }
    
    
    public void agregarEventos(Controlador controlador)
    {
        this.controlador=controlador;
        this.bnt_Jugar.addActionListener(controlador);
        this.btn_Instrucciones.addActionListener(controlador);
        this.btn_Salir.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bnt_Jugar = new javax.swing.JButton();
        btn_Instrucciones = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setDoubleBuffered(false);
        setEnabled(false);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(570, 803));
        setOpaque(false);
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(null);

        bnt_Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonJugar.png"))); // NOI18N
        bnt_Jugar.setActionCommand("Jugar");
        bnt_Jugar.setContentAreaFilled(false);
        bnt_Jugar.setDefaultCapable(false);
        add(bnt_Jugar);
        bnt_Jugar.setBounds(10, 10, 365, 103);

        btn_Instrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonInstrucciones.png"))); // NOI18N
        btn_Instrucciones.setActionCommand("Instrucciones");
        btn_Instrucciones.setContentAreaFilled(false);
        btn_Instrucciones.setFocusPainted(false);
        add(btn_Instrucciones);
        btn_Instrucciones.setBounds(60, 120, 257, 73);

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSalir.png"))); // NOI18N
        btn_Salir.setActionCommand("Salir");
        btn_Salir.setBorderPainted(false);
        btn_Salir.setContentAreaFilled(false);
        add(btn_Salir);
        btn_Salir.setBounds(290, 280, 125, 63);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_Jugar;
    private javax.swing.JButton btn_Instrucciones;
    private javax.swing.JButton btn_Salir;
    // End of variables declaration//GEN-END:variables
}
